site_name: MME Online
site_url: https://regensburger-forscher.de/mme
site_description: Online-Tutorial zum MME-Kurs
site_author: Alexander Bazo
copyright: MIT
theme: 
  name: yeti
  custom_dir: mme-template
plugins: [search]
markdown_extensions:
  - footnotes
  - admonition
nav:
  - Start: index.md
  - MME: 
    - Übersicht: MME/index.md
    - Softwareentwicklung mit Javascript: MME/class-introduction.md
    - Codequalität: MME/code-quality.md
    - Progammatische Manipulation des DOM: MME/dom-introduction.md
    - Javascript-Anwendungen strukturieren und gestalten: MME/closures-and-module-pattern.md
    - Versionskontrolle mit Git: MME/version-control.md
    - Den Event-Loop verstehen und verwenden: MME/event-loop.md
    - Client-Server-Kommunikation (AJAX und XMLHttpRequest): MME/ajax.md
    - Canvas, Video & Audio: MME/canvas-element.md
    - Datenspeicherung in Webanwendungen: MME/data-storage.md
    - Nebenläufigkeit im Browser: MME/webworkers.md
    - Einführung in die Node.js-Umgebung: MME/node-js.md
    - Komplexe Webanwendungen: MME/server-client-applications.md
    - Anforderungen erheben und dokumentieren: MME/requirements-for-student-projects.md
  - Demos:
      - Übersicht: Demos/index.md
      - Kanban-Board: Demos/kanban-board.md
      - Writer: Demos/writer.md
      - Simon Says: Demos/simon-says.md
      - Mensa App: Demos/mensa-app.md
      - Bundesliga-Tabelle: Demos/bundesliga.md
      - Ambi Player: Demos/ambi-player.md
      - Writer-Online: Demos/writer-online.md
  - Tutorials:
      - Übersicht: Tutorials/index.md
      - Der Projektordner: Tutorials/project-directory.md
      - Javascript im Browser: Tutorials/javascript-browser.md
      - Pair Programming: Tutorials/pair-programming.md
  - Ressourcen: resources.md
  - Impressum:
    - Autor: author.md
    - Impressum: impress.md
    - Lizenz: licence.md