site_name: MME Online
site_url: https://regensburger-forscher.de/mme
site_description: Online-Tutorial zum MME-Kurs
site_author: Alexander Bazo
copyright: MIT
theme: 
  name: yeti
  custom_dir: mme-template
plugins: [search, git-revision-date]
# extra_javascript:
#  - scripts/init.js
markdown_extensions:
  - footnotes
  - admonition
  - attr_list
nav:
  - Start: index.md
  - MME: 
    - Übersicht: MME/index.md
    - Einführung: MME/class-introduction.md
    - Progammatische Manipulation des DOM: MME/dom-introduction.md
    - Versionskontrolle mit Git: MME/version-control.md
#    - Codequalität: MME/code-quality.md
    - Javascript-Anwendungen strukturieren und gestalten: MME/closures-and-module-pattern.md
    - Den Event-Loop verstehen und verwenden: MME/event-loop.md
    - Client-Server-Kommunikation (AJAX und XMLHttpRequest): MME/ajax.md
    - Canvas, Video & Audio: MME/canvas-element.md
    - Datenspeicherung in Webanwendungen: MME/data-storage.md
#    - Nebenläufigkeit im Browser: MME/webworkers.md
#    - Einführung in die Node.js-Umgebung: MME/node-js.md
#    - Komplexe Webanwendungen: MME/server-client-applications.md
#    - Anforderungen erheben und dokumentieren: MME/requirements-for-student-projects.md
  - Demos:
      - Übersicht: Demos/index.md
      - ToDo-Liste: Demos/todo-list.md
      - Kanban-Board: Demos/kanban-board.md
#      - Writer: Demos/writer.md
      - Simon Says: Demos/simon-says.md
      - Time Tracker: Demos/time-tracker.md
      - Mensa App: Demos/mensa-app.md
      # - Bundesliga-Tabelle: Demos/bundesliga.md
      - Ambi Player: Demos/ambi-player.md
      - ToDo-Liste mit Datenbank: Demos/todo-list-db.md
      # - Writer-Online: Demos/writer-online.md
  - Aufgaben: 
      - Übersicht: Aufgaben/index.md
      - 01 | Countdown: Aufgaben//SS19-01-Countdown.md
      - 02 | Video Assistant: Aufgaben//SS19-02-Video-Assistant.md
  - Tutorials:
      - Übersicht: Tutorials/index.md
      - Die Arbeitsumgebung: Tutorials/work-environment.md
      - Der Projektordner: Tutorials/project-directory.md
      - Javascript im Browser: Tutorials/javascript-browser.md
      - Pair Programming: Tutorials/pair-programming.md
  - Ressourcen: 
      - Übersicht: Resources/index.md
#      - Literatur: Resources/reader.md
#      - Hilfe und Dokumentation: Resources/docs.md
#      - Werkzeuge: Resources/tools.md
  - Impressum:
    - Autor: author.md
    - Impressum: impress.md
    - Lizenz: licence.md